### ISSUE TITLE
scylla-bench exit with status -1 and log EOF after node reboot

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla-bench#40]
Test-id: 34cf5c4d-15f9-4125-b8c1-66873493ee6b
Number of scylladb nodes: 4

it's different from #37 that cannot create session , here exit during IO.

during node reboot disturbance scylla -bench exits with status -1 and log EOF after node reboot.
IO drop to 0.

**In sct.log**
2020-11-29 16:44:12.455: (ScyllaBenchEvent Severity.CRITICAL): type=failure node=Node longevity-counters-3h-4-3-loader-node-34cf5c4d-1 [3.251.65.128 | 10.0.1.75] (seed: False) stress_cmd=scylla-bench -workload=uniform -mode=counter_update -replication-factor=3 -partition-count=1000 -clustering-row-count=10 -concurrency 64 -duration 180m -validate-data error=Stress command completed with bad status -1: 2020/11/29 14:12:40 EOF
2020/11/29 14:12:40 EOF
2020/11/29 14:12:40 EOF
2020/11/29 14:12:40 EOF
2020
2020-11-29 16:44:12.458: (ScyllaBenchEvent Severity.CRITICAL): type=failure node=Node longevity-counters-3h-4-3-loader-node-34cf5c4d-1 [3.251.65.128 | 10.0.1.75] (seed: False) stress_cmd=scylla-bench -workload=uniform -mode=counter_read   -replication-factor=3 -partition-count=1000 -clustering-row-count=10 -concurrency 16 -duration 180m -validate-data error=Stress command completed with bad status -1: 2020/11/29 14:12:40 EOF
2020/11/29 14:12:40 EOF
2020/11/29 14:12:40 EOF
2020/11/29 14:12:40 EOF
2020

**Comment by roydahan** [comment]
@mmatczuk @piodul , we seprated this issue from the one in #37 where that issue happened due to client encryption.
Here, it's without client encryption but using a "counters" workload of scylla-bench.

we don't have much information except getting EOF after some time into the test.
Can you please take a look?

**Comment by piodul** [comment]
Log messages like:

```
2020/11/29 14:12:40 EOF
```

... in scylla-bench usually indicate that some connections to the cluster that the driver keeps was closed by the other side. Although it generates much spam, the event by itself is expected and harmless.

All occurences of this message can be attributed to a nemesis run which stops a Scylla instance:

`2020-11-29 14:12:40,337` <- One node was stopped due to disrupt_data_then_repair nemesis
`2020-11-29 14:36:13,958` <- One node was terminated due to disrupt_remove_node_then_add_node nemesis
`2020-11-29 14:55:38,275` <- One node was stopped due to disrupt_data_then_repair nemesis (second run of the first nemesis)
`2020-11-29 15:18:44,437` <- One of the nodes was hard-rebooted due to repair_streaming_err nemesis
`2020-11-29 15:43:36,282` <- One node was destroyed due to terminate_and_replace nemesis
`2020-11-29 16:22:24,253` <--+
`2020-11-29 16:26:48,132` <--+
`2020-11-29 16:29:48,390` <--+-- All those can be attributed to the same multiple_hard_reboot_node nemesis
`2020-11-29 16:34:02,972` <--+
`2020-11-29 16:37:49,771` <--+
`2020-11-29 16:41:37,069` <--+

The large number of EOF messages being printed around `2020-11-29 16:44:12,431` is because SCT seems to be printing all captured STDERR of the command when the command finishes its execution. Please take note of the timestamps:

```
2020-11-29 16:44:12,431 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > 2020/11/29 14:12:40 EOF
```

It's 16:44:12 vs. 14:12:40. The first indicates the time when all STDERR was dumped at once, while 14:12:40 indicates the actual time when the message was generated.

----

As for the non-zero exit code, I think this is because scylla-bench doesn't capture SIGTERM. It was sent by SCT during teardown:

```
< t:2020-11-29 16:44:12,240 f:sct_events.py   l:964  c:sdcm.sct_events      p:INFO  > 2020-11-29 16:44:12.228: (InfoEvent Severity.NORMAL): message=TEST_END
< t:2020-11-29 16:44:12,242 f:tester.py       l:173  c:silence              p:DEBUG > Finished 'Sending test end event'. No errors were silenced.
< t:2020-11-29 16:44:12,242 f:tester.py       l:1917 c:LongevityTest        p:INFO  > TearDown is starting...
< t:2020-11-29 16:44:12,242 f:tester.py       l:163  c:silence              p:DEBUG > Silently running 'stop_timeout_thread'
< t:2020-11-29 16:44:12,243 f:tester.py       l:165  c:silence              p:DEBUG > Finished 'stop_timeout_thread'. No errors were silenced.
< t:2020-11-29 16:44:12,243 f:tester.py       l:163  c:silence              p:DEBUG > Silently running 'stop_event_analyzer'
< t:2020-11-29 16:44:12,243 f:tester.py       l:165  c:silence              p:DEBUG > Finished 'stop_event_analyzer'. No errors were silenced.
< t:2020-11-29 16:44:12,243 f:tester.py       l:163  c:silence              p:DEBUG > Silently running 'stop_resources'
< t:2020-11-29 16:44:12,243 f:tester.py       l:1765 c:LongevityTest        p:DEBUG > Stopping all resources
< t:2020-11-29 16:44:12,361 f:remote_base.py  l:519  c:RemoteCmdRunner      p:DEBUG > Running command "pkill -f -TERM scylla-bench"...
< t:2020-11-29 16:44:12,427 f:base.py         l:140  c:RemoteCmdRunner      p:DEBUG > Command "pkill -f -TERM scylla-bench" finished with status 0
< t:2020-11-29 16:44:12,426 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "/$HOME/go/bin/scylla-bench -workload=uniform -mode=counter_update -replication-factor=3 -partition-count=1000 -cluste
ring-row-count=10 -concurrency 64 -duration 180m -validate-data -nodes 10.0.0.213"; Exit status: -1
< t:2020-11-29 16:44:12,430 f:base.py         l:146  c:RemoteCmdRunner      p:DEBUG > STDOUT: 50815ms       2.588671ms       1.769471ms       1.847815ms       
< t:2020-11-29 16:44:12,430 f:base.py         l:146  c:RemoteCmdRunner      p:DEBUG > 2h38m12.546513554s            33914    33914        0  18.382847ms      10.289151ms      4.161535ms       2.916351ms       2.588671ms       1.7
69471ms       1.859321ms       
< t:2020-11-29 16:44:12,430 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "/$HOME/go/bin/scylla-bench -workload=uniform -mode=counter_read   -replication-factor=3 -partition-count=1000 -cluste
ring-row-count=10 -concurrency 16 -duration 180m -validate-data -nodes 10.0.0.213"; Exit status: -1
< t:2020-11-29 16:44:12,431 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > STDERR: 2020/11/29 14:12:40 EOF
< t:2020-11-29 16:44:12,431 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > 2020/11/29 14:12:40 EOF
< t:2020-11-29 16:44:12,431 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > 2020/11/29 14:12:40 EOF
< t:2020-11-29 16:44:12,431 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > 2020/11/29 14:12:40 EOF
```

The teardown seems to have happened because the test reached the end of its duration:

```
< t:2020-11-29 13:44:11,144 f:sct_config.py   l:1232 c:sdcm.sct_config      p:INFO  > test_duration: 180
```

Instead, a SIGINT signal should be sent to scylla-bench - it handles that signal and tries to stop gracefully.

**Comment by shoshan** [comment]
moved to framework
